version: 2.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Debug

before_build:
  - nuget restore
  
build:
  project: Kaxaml.sln
  
artifacts:
  - path: Kaxaml\bin\Release
  
